/*
 * timer.c


 *
 *  Created on: Sep 17, 2017
 *      Author: Nicolas
 */
#include "timer.h"



void TIMER1_Init(void)// TIMER MODULE FUNCTION INITIALIZATION
{
	
	// NO CLOCK SELECTED (TPM DISABLED)
	TPM1SC_CLKSB=0;
	TPM1SC_CLKSA=0;
	
	TPM1SC_TOIE=1;//INTERRUPT ENABLE (OVERFLOW)
	TPM1SC_CPWMS=0;//ALL CHANNELS OPERATE AS I.C, O.C, edge-aligned PWM
	
	TPM1SC_PS=7;//TPM Clock Source Divides-by 128
	
	TPM1MOD=60000;//MODULE
		
	//CONFIGURE CHANNEL 0 AS I.C ->PTE2
	TPM1C0SC_CH0IE=1;//INTERRUPT ENABLE
	//MODE INPUT CAPTURE
	TPM1C0SC_MS0B=0;
	TPM1C0SC_MS0A=0;
	//CONFIGURE CAPTURE ON RISING OR FALLING EDGE
	TPM1C0SC_ELS0B=1;
	TPM1C0SC_ELS0A=1;
	
	//CONFIGURE CHANNEL 1 AS I.C.  ->PTE3
	TPM1C1SC_CH1IE=1;//INTERRUPT DISABLE
	//MODE OUTPUT CAPTURE
	TPM1C1SC_MS1B=0;
	TPM1C1SC_MS1A=0;
	//SET OUTPUT ON COMPARE
	TPM1C1SC_ELS1B=1; 
	TPM1C1SC_ELS1A=0;
	
	//CONFIGURE CHANNEL 2 AS I.C.  ->PTE3
		TPM1C2SC_CH2IE=1;//INTERRUPT DISABLE
		//MODE OUTPUT CAPTURE
		TPM1C2SC_MS2B=0;
		TPM1C2SC_MS2A=0;
		//SET OUTPUT ON COMPARE
		TPM1C2SC_ELS2B=1; 
		TPM1C2SC_ELS2A=0;
	
	TPM1SC_CLKSB=0;// BUS RATE CLOCK
	TPM1SC_CLKSA=1;
	
	TPM1C0SC;// 1.READING TPMxSC WHEN TOF IS SET
	TPM1C0SC_CH0F = 0; // 2. WRITING A LOGIC 0 TO CH0F
	TPM1C1SC;// 1.READING TPMxSC WHEN TOF IS SET
	TPM1C1SC_CH1F = 0; // 2. WRITING A LOGIC 0 TO CH0F
}


